### ISSUE TITLE
Redmine 3.1 fix (patch)

### ISSUE THREAD

**Issue by rtwo** [noma4i/Redmine-Touch#10]
I didn't want to open a pull request because I don't know if this would break support for earlier versions of redmine.

https://github.com/rtwo/Redmine-Touch/commit/a485b39b4a47adad01210546746f769415c8b55a

This is my fix to get the plugin working with redmine 3.1

I can open a regular pull request if you prefer.

**Comment by noma4i** [comment]
Iv checked against 2.5.2. It works so create a pull request )
